### ISSUE TITLE
Highlight the selected dataset in the plot

### ISSUE THREAD

**Issue by martinreiser** [tobias47n9e/innstereo#19]
Another thing that might be helpful is to highlight the selected datasets from the data window in the stereo plot. 

This could be done either with a different color (preferably one that is not selectable in the options) or by giving them thicker outlines.

Is this possible?

**Comment by tobias47n9e** [comment]
Hey Martin! That sounds like a great idea! I will see how that could be implemented.

**Comment by tobias47n9e** [comment]
Working on this one now. Requires a lot of changes, but I think the function structure will be much more cleaner at the end of it.

**Comment by tobias47n9e** [comment]
Now possible to highlight layers and subsets of a layer. Will make another release soon, so this can be tested:

 - https://github.com/tobias47n9e/innstereo/commit/f1d1d621821de21395c31e4fc0584c0a021b058c

**Comment by tobias47n9e** [comment]
@martinreiser Highlighting is now available in Beta 1. Currently points and lines are just displayed bolder than the current setting of the layer. Would there be a better way of highlighting symbols?

**Comment by martinreiser** [comment]
No, perfect!
