### ISSUE TITLE
Missing description

### ISSUE THREAD

**Issue by martinreiser** [tobias47n9e/innstereo#20]
The buttons "find mean vector" and "P-T axis calculation" are missing their pop-up descriptions (the ones in the black box).

**Comment by tobias47n9e** [comment]
Added the tooltips to both buttons:

 - https://github.com/tobias47n9e/innstereo/commit/ae7bde6cffd93dbc9b03c46b0f7913da4ccf7ef4

**Comment by tobias47n9e** [comment]
Fixed in Beta 1.
