### ISSUE TITLE
Filter JSON files in open-project filechooser

### ISSUE THREAD

**Issue by martinreiser** [tobias47n9e/innstereo#25]
Is it possible to have a dropdown menu in the load dialog window, where you can select the type of data shown in the list? Or somehow prioritize the JSON files in the list.
If you have several file types in one folder (or on the desktop) it takes a while to find the correct file.

**Comment by tobias47n9e** [comment]
Added JSON and "All Files" filter to the filechooser:

 - https://github.com/tobias47n9e/innstereo/commit/d2826787559713f7c0e873574350466de7f4d8c0

**Comment by tobias47n9e** [comment]
Fixed in Beta 2.
