### ISSUE TITLE
Remove highlighting when deselecting a layer

### ISSUE THREAD

**Issue by martinreiser** [tobias47n9e/innstereo#26]
Datasets should loose their highlighted status when the user clicks somewhere else in the window, or on the group layer. As of now, the last dataset remains highlighted.

**Comment by tobias47n9e** [comment]
Part of the problem fixed with this commit. Folders are now skipped by the highlighting function:

 - https://github.com/tobias47n9e/innstereo/commit/b74bc315c6983cda675132360a11c9944874efaa

**Comment by tobias47n9e** [comment]
Fixed in Beta 2.
