### ISSUE TITLE
Don't draw unchecked layers in highlight-mode

### ISSUE THREAD

**Issue by martinreiser** [tobias47n9e/innstereo#27]
The settings for the group layer need some revisions. When the group layer is unchecked, the datasets of the group layer or the last highlighted dataset are still shown in the stereo net. The group layer controls should override the layer controls. 
When the group layer is selected, the layers that are checked should appear in the stereo plot and unchecking should make all of them disappear.

**Comment by tobias47n9e** [comment]
I think this might be a problem of the highlight mode. I will take a look.

**Comment by tobias47n9e** [comment]
Highlighting now skips layers that are unchecked or if their parents are unchecked:

 - https://github.com/tobias47n9e/innstereo/commit/b74bc315c6983cda675132360a11c9944874efaa

**Comment by tobias47n9e** [comment]
Fixed in Beta 2.
